---
defaultWatchIntervalSeconds: 120
inClusterMode: true
## if inClusterMode is false, you must specify kubeconfig or k8s host and Bearer token pair.
#externalClusterKubeconfigPath: "<home>/.kube/config"
#externalClusterHost: "https://k8s.example.com/"
#externalClusterBearerToken: "LS0tLS1C....."
watch:
  - name: sample-secret
    namespace: sample-ns
    type: Opaque
    secretPath: /vault/secrets/sample-secret.yml
  - name: ingress-tls-certs
    namespace: sample-ns
    type: kubernetes.io/tls
    watchIntervalSeconds: 16
    secretPath: /vault/secrets/ingress-tls-certs.yml
  - name: docker-cred
    namespace: sample-ns
    type: kubernetes.io/dockerconfigjson
    secretPath: /vault/secrets/docker-cred.yml
    
    